---

- name: update mysql root password for all root accounts
  mysql_user:
    user: root
    host: '{{ item }}'
    password: '{{ mysql_root_password }}'
    state: present
  with_items:
   - 127.0.0.1
   - ::1
   - localhost

- name: copy the my.cnf file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: mysql_restart

- name: copy .my.cnf file with root password credentials
  template:
    src: root_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: '{{ item }}'
    state: absent
  with_items:
   - localhost
   - '{{ ansible_hostname }}'

- name: Dont allow root login remotely
  mysql_user:
    name: root
    host: '{{ ansible_hostname }}'
    state: absent

- name: remove the test database
  mysql_db:
    name: test
    state: absent